# Generated by Django 2.1 on 2018-08-31 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mercaderia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(max_length=100)),
                ('precio_compra', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('precio_venta', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('unidades_por_caja', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Mercaderia',
                'verbose_name_plural': 'Mercaderias',
            },
        ),
    ]
