# Generated by Django 2.1 on 2018-09-11 20:24

from django.db import migrations, models
import django.db.models.deletion
import mercaderias.models


class Migration(migrations.Migration):

    dependencies = [
        ('mercaderias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetallePromo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveSmallIntegerField()),
                ('mercaderia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mercaderias.Mercaderia')),
            ],
            options={
                'verbose_name': 'Detalle De Promo',
                'verbose_name_plural': 'Detalles de Promo',
            },
        ),
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(default=mercaderias.models.get_barcode, max_length=100, unique=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('nombre', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Promo',
                'verbose_name_plural': 'Promos',
            },
        ),
        migrations.AddField(
            model_name='detallepromo',
            name='promo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mercaderias.Promo'),
        ),
    ]
