# Generated by Django 2.1 on 2018-09-25 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercaderias', '0002_auto_20180911_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallepromo',
            name='cantidad',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
    ]
