# Generated by Django 2.1 on 2018-12-05 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercaderias', '0003_auto_20180925_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='promo',
            name='imagen_codigo',
            field=models.FileField(null=True, upload_to='barcodes/'),
        ),
    ]
