# Generated by Django 2.1 on 2019-01-25 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercaderias', '0004_auto_20181204_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mercaderia',
            name='precio_compra',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='mercaderia',
            name='precio_venta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
