# Generated by Django 2.1 on 2019-01-25 00:02

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalledeventa',
            name='ganancia',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=9),
        ),
        migrations.AlterField(
            model_name='detalledeventa',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
